export const INCREASE_COUNTER="INCREASE_COUNTER"
export const DECREASE_COUNTER="DECREASE_COUNTER"
export const FETCH_POST="FETCH_POST"
export const FETCH_TODO="FETCH_TODO"
export const FETCH_COMMENT="FETCH_COMMENT"
export const FETCH_USER="FETCH_USER"







export const SET_POST_DATA="SET_POST_DATA"
export const SET_COMMENT_DATA="SET_COMMENT_DATA"
export const SET_USER_DATA="SET_USER_DATA"
export const SET_TODO_DATA="SET_TODO_DATA"